apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip_detection
  namespace: abrarvan
spec:

  replicas: 1
  selector:
    matchLabels:
      app: ip_detection
  template:
    metadata:
      labels:
        app: ip_detection
    spec:
      containers:
        - name: ip_detection
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: ip_detection
  namespace: abrarvan
spec:
  type: NodePort
  selector:
    app: ip_detection
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30206
